name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:14.17.0
    services:
      postgres:
        image: postgres:13-alpine
        env:
          PGDATABASE: realworld
          POSTGRES_DB: realworld
          PGUSER: admin
          POSTGRES_USER: admin
          PGPASSWORD: password
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installling dependencies
        run: npm install

      - name: Rebuild Argon2
        run: npm rebuild argon2 --build-from-source

      - name: Lint check
        run: npm run lint

      - name: Prisma migration
        run: npm run db:push
        env:
          DATABASE_URL: postgresql://admin:password@postgres:5432/realworld

      - name: Test & Coverage
        run: npm run cover
        env:
          DATABASE_URL: postgresql://admin:password@postgres:5432/realworld
          TOKEN_SECRET: 881A08FD732052323526265B87FAD0D7DA192196C46F5367E9D0C9152110A7F4
          PORT: 3000

      # Remove this comment when merged
      #- name: Upload to Codecov
      #  run: bash <(curl -s https://codecov.io/bash)
